[package]
cjc-version = "1.0.0"
name = "pipeline"
description = "Sample Cangjie project used to verify the CI unit-test pipeline."
version = "0.1.0"
output-type = "executable"
src-dir = ""
target-dir = "target"

[profile.test]
customized-option = "--display-level=FULL"
